# Generated by Django 4.0.6 on 2023-08-15 10:50

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('date', models.DateField(default=datetime.date.today)),
                ('department', models.CharField(choices=[('General Health', 'General Health'), ('Cardiology', 'Cardiology'), ('Dental', 'Dental'), ('Medical Research', 'Medical Research')], max_length=40)),
                ('mobileno', models.CharField(max_length=15)),
                ('msg', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
